### ISSUE TITLE
send users directly to anc page?

### ISSUE THREAD

**Issue by stvnrlly** [codefordc/ancfinder#141]
Unless many people are searching multiple addresses, it might make more sense to just send people directly to the page of the address that they search. If necessary, we could add a `search again` button to the navbar or something for people who want to do multiple searches.

**Comment by stvnrlly** [comment]
Let's do this.

**Comment by mdelcambre** [comment]
Not sure that I agree (or disagree). One very nice thing about the current system allows users to quickly identify and correct issues with the geocoding.

**Comment by stvnrlly** [comment]
@mdelcambre Do you mean that if a user searches the wrong address, the current system allows for quick correction, or are you referring to something more technical? If the former, having an obvious `search again` button might alleviate that issue.

The benefit of this change is that it exposes more people to more information about their ANC. Currently, many visitors don't get beyond our main page. If we can create more civic engagement opportunities without making it harder to use the site, I think that's a win. This will definitely require some user testing, though.

**Comment by mdelcambre** [comment]
I was thinking with the current implementation of the ANC info, I find it harder to notice that the geocoder got the wrong address. Lets say I live at 1405 Monroe St NW. But forget to put on the NW.

When I search that, I quickly see that the map is definitely not right (partially because of the marker and greater zoom level. And partially because the sparse info points my eyes to look at the map.
![currentfirstpage](https://cloud.githubusercontent.com/assets/117248/7417752/5c54ea94-ef36-11e4-855d-2e4128c71adc.PNG)

However, I don't notice that as quickly (if at all) on the details page (as currently implemented). An additional note is that if you don't get the information from the first page, it is not obvious who your ANC is (the light highlight is easy to miss).
![secondpage](https://cloud.githubusercontent.com/assets/117248/7417755/63a8734c-ef36-11e4-803b-cefd51994bbf.PNG)

Now I agree that changes could be made to present that information in an easy to notice way in the details page (not sure exactly what that would look like). But just wanted to say that I am not sure we should just change it to point directly to the second page without potentially thinking about the way the information is presented.

**Comment by zachschalk** [comment]
I agree that sending users directly to the ANC overview page would be an improvement (in that right now all the valuable information found on the page is hidden behind too many clicks) but that the current organization of the page would need to be updated if this was the initial search landing page. A few changes that could improve the usability of the page come to mind:

1) Addressing the aforementioned map issue is important. I wonder if it would be possible to make the map viewer a little bigger and maybe use the map layering currently on the initial search landing page (for the reasons mentioned above). I also wonder if changing the colors used to differentiate the ANCs might make it easier to identify them on the map.

2) Either a search again button (mentioned above) or just a permanent search bar built into the top menu could help with multiple searches.

3) The information about the specific commissioner for the address entered needs to be better highlighted on the ANC page (so basically integrating the info that currently is prominently displayed on the search landing page)

4) I would also switch the positions of the map and the "key documents" section. Right now, there's a documents tab at the top of the page, so the key documents section seems a bit redundant. Also, the map is the most visually appealing part of the page, and locating it under the documents section only pushes it down the page and pulls the user's eye away. I think someone looking for documents (or looking to upload them) would either click the documents tab or be willing to scroll around the page to find it.

**Comment by stvnrlly** [comment]
I think that I agree with everything @mdelcambre and @zachschalk have said here. There's a start by @emanuelfeld in #145, but I don't believe that it incorporates the things we're talking about here yet.
