### ISSUE TITLE
Document search

### ISSUE THREAD

**Issue by stvnrlly** [codefordc/ancfinder#75]
Users should be able to search the uploaded documents, either within the ANC or across the pool of documents. In addition to being generally useful, this would help keep information accessible if ANC boundaries change at a later date.

**Comment by emkap01** [comment]
This would be a hugely useful feature. For example, imagine if a developer petitions an ANC for permission to build a new apartment complex.  

Throughout the life of the development project multiple records will be generated that could get uploaded to ANC Finder, such as meeting minutes from every appearance the developer makes in front of the ANC, related permits and applications etc. 

Being able to search on the developer and/or application itself and pull back all related documents would help users understand much more easily how that project is impacting their community, instead of having to search for those same records across multiple stove-piped repositories.  

That in turn would probably incentivize more users to upload more documents, since ANC Finder would be the only place where all those records could be centralized and searchable.
